version: '3.7'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      - TZ=${TIMEZONE}
      - WEBPASSWORD=${PIHOLE_PASSWORD}
      - FTLCONF_LOCAL_IPV4=${PIHOLE_HOST_IP}
      #
      - PIHOLE_DNS_=1.1.1.1;1.0.0.1;2606:4700:4700::1111;2606:4700:4700::1001;208.67.222.222;208.67.220.220;2620:119:35::35;2620:119:53::53;8.8.8.8;8.8.4.4;2001:4860:4860:0:0:0:0:8888;2001:4860:4860:0:0:0:0:8844
      - DNSSEC=true
      #
      - REV_SERVER=true
      - REV_SERVER_DOMAIN=${PIHOLE_DOMAIN_NAME}
      - REV_SERVER_TARGET=${PIHOLE_ROUTER_IP}
      - REV_SERVER_CIDR=${PIHOLE_REVERSE_DNS}
      #
      - DHCP_ACTIVE=false
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 1.0.0.1
      - 208.67.222.222
    cap_add:
      - NET_ADMIN
    restart: always
