version: '3.6'

services:
  imapfilter:
    command: imapfilter
    container_name: imapfilter
    build:
      context: ./imapfilter
    volumes:
      - ~/.imapfilter:/root/.imapfilter:ro
    working_dir: /root

  imapfilter_archive:
    command: imapfilter -c /root/.imapfilter/archive.lua
    container_name: imapfilter
    build:
      context: ./imapfilter
    volumes:
      - ~/.imapfilter:/root/.imapfilter:ro
    working_dir: /root

  imapfilter_daily:
    command: imapfilter -c /root/.imapfilter/daily.lua
    container_name: imapfilter
    build:
      context: ./imapfilter
    volumes:
      - ~/.imapfilter:/root/.imapfilter:ro
    working_dir: /root

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    domainname: renatius.net
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '80:80/tcp'
    environment:
      PIHOLE_DOMAIN: 'renatius.net'
      PIHOLE_DNS_: '1.1.1.1;1.0.0.1;2606:4700:4700::1111;2606:4700:4700::1001;208.67.222.222;208.67.220.220;2620:119:35::35;2620:119:53::53;8.8.8.8;8.8.4.4;2001:4860:4860:0:0:0:0:8888;2001:4860:4860:0:0:0:0:8844'
      DNSSEC: 'true'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
